# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x0btaskPackage\"\x0e\n\x0cNoParameters\"G\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x13\n\x06jiraId\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_jiraId\")\n\x05Tasks\x12 \n\x05tasks\x18\x01 \x03(\x0b\x32\x11.taskPackage.Task\"$\n\x0bTransaction\x12\x15\n\rtransactionId\x18\x01 \x01(\t\"&\n\x0cTransactions\x12\x16\n\x0etransactionIds\x18\x01 \x03(\t2\x98\x02\n\x0bTaskService\x12\x39\n\ncreateTask\x12\x11.taskPackage.Task\x1a\x18.taskPackage.Transaction\x12:\n\x08getTasks\x12\x19.taskPackage.NoParameters\x1a\x11.taskPackage.Task0\x01\x12\x42\n\x10streamCreateTask\x12\x11.taskPackage.Task\x1a\x19.taskPackage.Transactions(\x01\x12N\n\x1bstreamContinuesTaskCreation\x12\x11.taskPackage.Task\x1a\x18.taskPackage.Transaction(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_NOPARAMETERS']._serialized_start=27
  _globals['_NOPARAMETERS']._serialized_end=41
  _globals['_TASK']._serialized_start=43
  _globals['_TASK']._serialized_end=114
  _globals['_TASKS']._serialized_start=116
  _globals['_TASKS']._serialized_end=157
  _globals['_TRANSACTION']._serialized_start=159
  _globals['_TRANSACTION']._serialized_end=195
  _globals['_TRANSACTIONS']._serialized_start=197
  _globals['_TRANSACTIONS']._serialized_end=235
  _globals['_TASKSERVICE']._serialized_start=238
  _globals['_TASKSERVICE']._serialized_end=518
# @@protoc_insertion_point(module_scope)
